#!/usr/bin/env node

var Path = require('path');
require(Path.join(process.cwd(), 'core', 'globals'));

var config = requireRoot('core/config')
  , client = requireRoot('core/lib/elasticsearch/client')
  , schema = requireRoot('db/schema');

client.indices.create({index: config.elasticsearch.index}, function(err, response, status){
  if (null != err) {
    console.error(err)
    process.exit(1);
  }

  if (!(response.ok === true && status === 200)) {
    if (status !== 200)
      console.error('Expected 200, but status was %s', status);
    if (response.ok !== true)
      console.error('Expected true, but response.ok was %s', response.ok);
    process.exit(1)
  }

  client.indices.putMapping({body: schema, index: config.elasticsearch.index, type: "show"}, function(err, response, status){
    if (null != err) {
      console.error(err)
      process.exit(1);
    }

    if (!(response.ok === true && status === 200)) {
      if (status !== 200)
        console.error('Expected 200, but status was %s', status);
      if (response.ok !== true)
        console.error('Expected true, but response.ok was %s', response.ok);
      process.exit(1)
    }

    console.log('Created %s index and %s type', config.elasticsearch.index, 'show');
    process.exit(0);
  });
});
